services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

    restart: always


  airflow-apiserver:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "false"

      AIRFLOW__API_AUTH__JWT_SECRET: "stockholm-transit-local-dev-secret"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

      - ../src:/opt/airflow/project/src
      - ../data:/opt/airflow/project/data
      - ../.env:/opt/airflow/project/.env

    ports:
      - "8080:8080"

    command: api-server

    restart: always


  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "false"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

      - ../src:/opt/airflow/project/src
      - ../data:/opt/airflow/project/data
      - ../.env:/opt/airflow/project/.env

    command: dag-processor

    restart: always


  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      postgres:
        condition: service_healthy

      airflow-apiserver:
        condition: service_started

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "false"

      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW__API_AUTH__JWT_SECRET: "stockholm-transit-local-dev-secret"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

      - ../src:/opt/airflow/project/src
      - ../data:/opt/airflow/project/data
      - ../.env:/opt/airflow/project/.env

    command: scheduler

    restart: always


volumes:
  postgres-db-volume: